
enum ItemId {
  NO_ITEM = 0,
  NAIL = 1,
  CANDLE = 2,
  PENNY = 3,
  BASEBALL = 4,
  MATH_TEXTBOOK = 5,
  ENGLISH_TEXTBOOK = 6,
  SCIENCE_TEXTBOOK = 7,
  HISTORY_TEXTBOOK = 8,
  TEAPOT = 9,
  SPIDER = 10,
  DOLLAR_BILL = 11,
  BRIEFCASE = 12,
  GOLD_BAR = 13,
  GOLD_STACK = 14,
  CHEST = 15,
}
